const input=document.querySelector('#bot-search'),results=document.querySelector('#bot-results'),status=document.querySelector('#bot-search-status'),themeToggle=document.querySelector('#theme-toggle');
const normalise=value=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/gi,'').toLowerCase();
const isSubsequence=(query,value)=>{let index=0;for(const character of value){if(character===query[index])index+=1;}return index===query.length;};
const distance=(left,right)=>{let previous=Array.from({length:right.length+1},(_,index)=>index);for(let row=1;row<=left.length;row+=1){const current=[row];for(let column=1;column<=right.length;column+=1)current[column]=Math.min(current[column-1]+1,previous[column]+1,previous[column-1]+(left[row-1]===right[column-1]?0:1));previous=current;}return previous[right.length];};
const names=["xXShadowXx","Novâa","Viper9","Echo_Strike","FrostByte_13","SilentRogue","Arcane","KindaMeh","RazorEdge","Holo_Pulse","DontSwipeLeft","DriftKing","Luma_Exile","GloomWolf_404","PixelRaptor","ZenSeeker","K1ngmaker","Neon_Spectre","PhantomCore","ByteWarden","Iron_Falcon","CrashCaster","VelvetStorm","StaticShock","Outlaaaw","CipherNode","SillyMe","AmberRift","RogueNova","Steel_Sentry","0oLunarEcho0","Alpha_µ","Blitz_Fang","Zouiiiip","GrimJester666","SpectraHAHA","NovaHeX","QuickSilver","Thornback","ChompChomp","Mistral_04","OmegaPulseX","NeonVoodoo","Apex_Scout","Frost_Clutch","SirenStrike","TurboMoth","NullVector","RazorWing","MirroredMind","BoltCrusader","Wraith_0x","CrypticFox","I_GlitchMage_I","McCoffee","Pyro_Arc_One","ShadowGlyph","Kinetic_Pie","Mystic_Vex","AtlasRunner8","Ball_of_furr","ZenithEdith","Phantomhive","QuakeFury2","Quirky_Billy90","NeonEcho_17","Scarabi","HarbingerXOXO","NoRoots","Vex_Operator","IronClaw","LunaDart","Pulse_Rook","_NightFable_","Solstice","ByteBandit","Drift_Protocol","Arcflash","GhostRun5","VortexVandal","RazorSoul_21","NonBinarySiren","Echo_Wolf","Crimson_Grid","marrymebertie","Phalanx","NeonRift","Void_Sprinter","Tidal_Arc","LunarShade_77","Mistwalker","BlitzPellet","NovaGunner","Khaos_Unit","Pixel_Jackal","Silent_Trigger","StormBound1","RogueSignal","zzzzzGlider","sofresh","NightPulse","Iseedeadlombax","FixatedOnYou","Fragile_Fox","SoPeculiar","Void_Cadet","Warp_Rider","AlwaysOnline","Azure_Scourge","Gh0stRunner","TearUanew1","ShadowCartel","From_the_deep","BoredHunter","xKab00mx","gem1n1","unfathomable","Glowy_Algae","SlippyJimmy","OneTwoFive","Yeahyeahyeah","thebrutalist","LuckyHour","NoFairFight","Ignorant_Snob","g0dl1ke","flippinamazing","VHSForever","wordsaredead","LOOTLOOTLOOT","Headhunterzz","FeuerFrei","MCSyndrom","Yassssss","Soulless_Rat","Fnatics","Juliodelavega","imacreep","Froggy75","Raaaw","Neogarden","Coldarmor","StormWisp4U","Blade_Matron","Midnight_7th","Kamikuro","Silent_Orb","NOTaBot","Vilified","TheRealQwark","MirageScout","Deathon2legs","SteelDrift","Empyre","Ghostly_Seed","Nightfall_007","CrookedHalo","LucidWarden","Phant0mL0rd","fancy_pants","PumpedUpKicks","Suuub0","Nullify","JokeZonU","Omega_Thread","PixelCobra","LumenKaren","MrsGoodenough","Agni_1994","X_Shaktimaan_7","Krur_89","Albrat0s","Unique499","FratBoy","TezTalwar","JollyGoodIdea","Surya","dontpanicnow","FreeTheMeeple","earthquaker","Zzbrrapapalipa","Iv0ryKrane","Fractal_Panda","WorkSimulator3","lukewarm","CrispAF","ECHOecho","Udontslayyy","CiderPunk","Calamity_Jeff","Magic_Mice","ieedeadmeeple","FiatLux","thatsabummer","Not1but2","Whataboutus","TastySamosa","TOPLANEORAFK"];
function render(matches){results.replaceChildren(...matches.map(name=>{const item=document.createElement('li');item.textContent=name;return item;}));}
function search(){const query=normalise(input.value);if(!query){render([]);status.textContent=`Start typing to search ${names.length} bot names.`;return;}const matches=names.map(name=>{const value=normalise(name),included=value.includes(query),subsequence=isSubsequence(query,value),difference=distance(query,value);return {name,included,subsequence,difference};}).filter(match=>match.included||match.subsequence||match.difference<=Math.max(1,Math.floor(query.length/3))).sort((left,right)=>Number(right.included)-Number(left.included)||Number(right.subsequence)-Number(left.subsequence)||left.difference-right.difference||left.name.localeCompare(right.name)).slice(0,60).map(match=>match.name);render(matches);status.textContent=matches.length?`${matches.length} matching bot name${matches.length===1?'':'s'}.`:'No matching bot names.';}
search();
input.addEventListener('input',search);
themeToggle.addEventListener('click',()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;localStorage.setItem('rangerRumbleTheme',theme);themeToggle.textContent=theme==='dark'?'☾':'☀';themeToggle.setAttribute('aria-label',`Switch to ${theme==='dark'?'light':'dark'} mode`);});
const initialTheme=document.documentElement.dataset.theme;themeToggle.textContent=initialTheme==='dark'?'☾':'☀';themeToggle.setAttribute('aria-label',`Switch to ${initialTheme==='dark'?'light':'dark'} mode`);
